credentials:
  usernames:
    testinstance:
      email: fbco.test.CapPlanSim@testserver.com
      name: FBCOTestServer
      password: $2b$12$hsGQ17xzeSD5SWvrTKPd7euISYOir21AS0OezjmPSh3uZDGNkX9l2 # Placeholder for hashed password of 'abc'
cookie:
  expiry_days: 90
  key: FBCOTestServerHashed@20230911CapacityPlanning # Must be string
  name: FBCO Test
preauthorized:
  emails:
  - marc.castro@tdcx.com